- name: Launch EC2
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: myInstance
        key_name: my-key
        region: us-east-1
        instance_type: t3.micro
        image_id: ami-07041441b708acbd6
        wait: yes
